tag = "dugdug-actions"
writes = [
    "dugdug-Miner",
    "dugdug-Mine",
    "dugdug-ERC20MetadataModel",
    "dugdug-ERC20BalanceModel",
    "dugdug-ERC20AllowanceModel",
    "dugdug-ERC20BridgeableModel",
    "dugdug-InitializableModel",
]
