kind = "DojoContract"
class_hash = "0x7879fc69e2d6d29e17aa0d3028d2bb2d6c6669cb919d641b4b2a5f5e09ec413"
original_class_hash = "0x7879fc69e2d6d29e17aa0d3028d2bb2d6c6669cb919d641b4b2a5f5e09ec413"
base_class_hash = "0x0"
abi = "manifests/release/base/abis/contracts/dugdug-actions-3a561b6b.json"
reads = []
writes = []
init_calldata = []
tag = "dugdug-actions"
systems = [
    "spawn_miner",
    "buy_axe",
    "start_mining",
    "check_mining",
    "leave_mine",
    "create_mine",
]
manifest_name = "dugdug-actions-3a561b6b"
