[world]
kind = "WorldContract"
class_hash = "0xa349b743d361ce4567361475a89b84a386bb383448c6926954e5fe0b525597"
original_class_hash = "0xa349b743d361ce4567361475a89b84a386bb383448c6926954e5fe0b525597"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x340ea7578c677d1ef6e5ca96035a3e1058e244132e7b82e5867d4bcc91c9d37"
transaction_hash = "0x283d5313d6e516e7f85dfc63741a39fd30dabedec37a8babf5d722449cd5113"
block_number = 3
seed = "dugdug"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x54650e2c3278fa42b3de565841b132007ef03cfb4e30db9c5dee68d9083b697"
class_hash = "0xf4608917128ca9c58395ac2317df3057293b058765387ece22b2ea8dc8e7e1"
original_class_hash = "0xf4608917128ca9c58395ac2317df3057293b058765387ece22b2ea8dc8e7e1"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/dugdug-Axe-35116bd0.json"
reads = []
writes = [
    "dugdug-ERC20MetadataModel",
    "dugdug-ERC20BalanceModel",
    "dugdug-ERC20AllowanceModel",
    "dugdug-ERC20BridgeableModel",
    "dugdug-InitializableModel",
]
init_calldata = []
tag = "dugdug-Axe"
systems = [
    "initializer",
    "mint_from",
    "burn_from",
]
manifest_name = "dugdug-Axe-35116bd0"

[[contracts]]
kind = "DojoContract"
address = "0x4421a3475b1d5adc5876ce0616f64ea3b5020ee710e7c168ca417c3c8b2274"
class_hash = "0x5cd78de3f52ec0cc54de20c477f13b5156f77b8f679f56d71cec6bdbf530562"
original_class_hash = "0x5cd78de3f52ec0cc54de20c477f13b5156f77b8f679f56d71cec6bdbf530562"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/dugdug-Mineral-4088245c.json"
reads = []
writes = [
    "dugdug-ERC20MetadataModel",
    "dugdug-ERC20BalanceModel",
    "dugdug-ERC20AllowanceModel",
    "dugdug-ERC20BridgeableModel",
    "dugdug-InitializableModel",
]
init_calldata = []
tag = "dugdug-Mineral"
systems = [
    "initializer",
    "mint_from",
    "burn_from",
]
manifest_name = "dugdug-Mineral-4088245c"

[[contracts]]
kind = "DojoContract"
address = "0x7a5c8d90c93dced85e1e96ad39469b5d28670c651667a02955588854ae5461d"
class_hash = "0x78e0479ee03948082b3125189f6ee65d621d0fa33b5361fd42ecb220159179"
original_class_hash = "0x78e0479ee03948082b3125189f6ee65d621d0fa33b5361fd42ecb220159179"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/dugdug-actions-3a561b6b.json"
reads = []
writes = [
    "dugdug-Miner",
    "dugdug-Mine",
    "dugdug-ERC20MetadataModel",
    "dugdug-ERC20BalanceModel",
    "dugdug-ERC20AllowanceModel",
    "dugdug-ERC20BridgeableModel",
    "dugdug-InitializableModel",
]
init_calldata = []
tag = "dugdug-actions"
systems = [
    "spawn_miner",
    "buy_axe",
    "start_mining",
    "check_mining",
    "leave_mine",
    "create_mine",
]
manifest_name = "dugdug-actions-3a561b6b"

[[models]]
kind = "DojoModel"
class_hash = "0x23f63e316921e339f9716b6674f2516981ec2a78caa8a168b7f63ad037a4b19"
original_class_hash = "0x23f63e316921e339f9716b6674f2516981ec2a78caa8a168b7f63ad037a4b19"
abi = "manifests/dev/deployment/abis/models/dugdug-ERC20AllowanceModel-32067bc6.json"
tag = "dugdug-ERC20AllowanceModel"
qualified_path = "origami_token::components::token::erc20::erc20_allowance::erc_20_allowance_model"
manifest_name = "dugdug-ERC20AllowanceModel-32067bc6"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "spender"
type = "ContractAddress"
key = true

[[models.members]]
name = "amount"
type = "u256"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x71008e5ba49adb3d693912ab2358266b65e6c71cdbc67a2bc5fc616ddf6f64b"
original_class_hash = "0x71008e5ba49adb3d693912ab2358266b65e6c71cdbc67a2bc5fc616ddf6f64b"
abi = "manifests/dev/deployment/abis/models/dugdug-ERC20BalanceModel-168c1bfc.json"
tag = "dugdug-ERC20BalanceModel"
qualified_path = "origami_token::components::token::erc20::erc20_balance::erc_20_balance_model"
manifest_name = "dugdug-ERC20BalanceModel-168c1bfc"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "account"
type = "ContractAddress"
key = true

[[models.members]]
name = "amount"
type = "u256"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1d83e6ddb8065b7fc080e9c99ec88b2409cbea751fceea9309938b16c762caf"
original_class_hash = "0x1d83e6ddb8065b7fc080e9c99ec88b2409cbea751fceea9309938b16c762caf"
abi = "manifests/dev/deployment/abis/models/dugdug-ERC20BridgeableModel-5e4d03b4.json"
tag = "dugdug-ERC20BridgeableModel"
qualified_path = "dugdug::tokens::AXE::erc_20_bridgeable_model"
manifest_name = "dugdug-ERC20BridgeableModel-5e4d03b4"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "l2_bridge_address"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1c6c80a3bcc3cabce57054f44fe3b9a823d13372157fc28702db05b1db13bd2"
original_class_hash = "0x1c6c80a3bcc3cabce57054f44fe3b9a823d13372157fc28702db05b1db13bd2"
abi = "manifests/dev/deployment/abis/models/dugdug-ERC20MetadataModel-33e77978.json"
tag = "dugdug-ERC20MetadataModel"
qualified_path = "origami_token::components::token::erc20::erc20_metadata::erc_20_metadata_model"
manifest_name = "dugdug-ERC20MetadataModel-33e77978"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "ByteArray"
key = false

[[models.members]]
name = "symbol"
type = "ByteArray"
key = false

[[models.members]]
name = "decimals"
type = "u8"
key = false

[[models.members]]
name = "total_supply"
type = "u256"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x719b252d6fa2e664cfe8c08cdd2018fff8c0573dc1731e8f628e16ad0f29f4b"
original_class_hash = "0x719b252d6fa2e664cfe8c08cdd2018fff8c0573dc1731e8f628e16ad0f29f4b"
abi = "manifests/dev/deployment/abis/models/dugdug-InitializableModel-4681648a.json"
tag = "dugdug-InitializableModel"
qualified_path = "origami_token::components::security::initializable::initializable_model"
manifest_name = "dugdug-InitializableModel-4681648a"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "initialized"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5a5e67896b3e178ad505c62c62bb61fdd80607cc27af6d920ac1e3f62a5b050"
original_class_hash = "0x5a5e67896b3e178ad505c62c62bb61fdd80607cc27af6d920ac1e3f62a5b050"
abi = "manifests/dev/deployment/abis/models/dugdug-Mine-4f01e10d.json"
tag = "dugdug-Mine"
qualified_path = "dugdug::models::mine"
manifest_name = "dugdug-Mine-4f01e10d"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "current_status"
type = "MineStatus"
key = false

[[models.members]]
name = "mining_state"
type = "u32"
key = false

[[models.members]]
name = "selfless_miners"
type = "u32"
key = false

[[models.members]]
name = "selfish_miners"
type = "u32"
key = false

[[models.members]]
name = "stability"
type = "u32"
key = false

[[models.members]]
name = "efficiency"
type = "u32"
key = false

[[models.members]]
name = "seed"
type = "u128"
key = false

[[models.members]]
name = "mineral_payout"
type = "u64"
key = false

[[models.members]]
name = "last_miner"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x50f1db7c94f8ae69569496bf28a4a0f0c6db74d3aa700b88b88664aad4cfe0c"
original_class_hash = "0x50f1db7c94f8ae69569496bf28a4a0f0c6db74d3aa700b88b88664aad4cfe0c"
abi = "manifests/dev/deployment/abis/models/dugdug-MineUpdate-1a1d7f54.json"
tag = "dugdug-MineUpdate"
qualified_path = "dugdug::events::mine_update"
manifest_name = "dugdug-MineUpdate-1a1d7f54"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "time"
type = "u64"
key = false

[[models.members]]
name = "mine"
type = "Mine"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5dbdd394816a3ea86c6a637bba0824c13a763c06c1848a4c96e4a53f123afaf"
original_class_hash = "0x5dbdd394816a3ea86c6a637bba0824c13a763c06c1848a4c96e4a53f123afaf"
abi = "manifests/dev/deployment/abis/models/dugdug-Miner-73834205.json"
tag = "dugdug-Miner"
qualified_path = "dugdug::models::miner"
manifest_name = "dugdug-Miner-73834205"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "owner"
type = "ContractAddress"
key = false

[[models.members]]
name = "xp"
type = "u32"
key = false

[[models.members]]
name = "health"
type = "MinerHealth"
key = false

[[models.members]]
name = "gear_level"
type = "GearLevel"
key = false

[[models.members]]
name = "status"
type = "MinerStatus"
key = false

[[models.members]]
name = "choice"
type = "MinerChoice"
key = false

[[models.members]]
name = "last_checkup"
type = "u64"
key = false

[[models.members]]
name = "entered_mine"
type = "u64"
key = false

[[models.members]]
name = "mine_id"
type = "u32"
key = false

[[models.members]]
name = "seed"
type = "u128"
key = false

[[models.members]]
name = "birthtime"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7380547bc745d1603929e63921de403a9b6e3475598984afb5d96f141c6d8fa"
original_class_hash = "0x7380547bc745d1603929e63921de403a9b6e3475598984afb5d96f141c6d8fa"
abi = "manifests/dev/deployment/abis/models/dugdug-MinerSpawned-4dd46768.json"
tag = "dugdug-MinerSpawned"
qualified_path = "dugdug::events::miner_spawned"
manifest_name = "dugdug-MinerSpawned-4dd46768"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "time"
type = "u64"
key = false

[[models.members]]
name = "miner"
type = "Miner"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3957a2e804ec76d1bdd5c1d58388260f6824b8234f29c31770469b13e8ea169"
original_class_hash = "0x3957a2e804ec76d1bdd5c1d58388260f6824b8234f29c31770469b13e8ea169"
abi = "manifests/dev/deployment/abis/models/dugdug-MineralFound-31a5ca33.json"
tag = "dugdug-MineralFound"
qualified_path = "dugdug::events::mineral_found"
manifest_name = "dugdug-MineralFound-31a5ca33"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "time"
type = "u64"
key = false

[[models.members]]
name = "mineral"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x50234f7289b557f13786ce312d672f9e6ef80fa5a13bd3196a7c69b069d4c2b"
original_class_hash = "0x50234f7289b557f13786ce312d672f9e6ef80fa5a13bd3196a7c69b069d4c2b"
abi = "manifests/dev/deployment/abis/models/haiku-MineralFoundHaiku-108fdf96.json"
tag = "haiku-MineralFoundHaiku"
qualified_path = "dugdug::events::mineral_found_haiku"
manifest_name = "haiku-MineralFoundHaiku-108fdf96"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "timestamp"
type = "u64"
key = false

[[models.members]]
name = "seed"
type = "u128"
key = false

[[models.members]]
name = "minerals"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1db14cac86795ac0ff8dac3d7e426273d98e209007288169b9d8353bcbdd0e"
original_class_hash = "0x1db14cac86795ac0ff8dac3d7e426273d98e209007288169b9d8353bcbdd0e"
abi = "manifests/dev/deployment/abis/models/haiku-PromptMessage-461b562f.json"
tag = "haiku-PromptMessage"
qualified_path = "haiku_event::prompt_message"
manifest_name = "haiku-PromptMessage-461b562f"

[[models.members]]
name = "identity"
type = "ContractAddress"
key = true

[[models.members]]
name = "event_id"
type = "u32"
key = true

[[models.members]]
name = "event_tag"
type = "ByteArray"
key = false

[[models.members]]
name = "prompt"
type = "ByteArray"
key = false

[[models.members]]
name = "timestamp"
type = "u64"
key = false
