kind = "DojoContract"
class_hash = "0x4f10da1ba615523c1a4b9e2ad40df134edbcf2d971a1074efbd9772c86c2173"
original_class_hash = "0x4f10da1ba615523c1a4b9e2ad40df134edbcf2d971a1074efbd9772c86c2173"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/dojo_starter-actions-7a1c7102.json"
reads = []
writes = []
init_calldata = []
tag = "dojo_starter-actions"
systems = [
    "spawn",
    "move",
]
manifest_name = "dojo_starter-actions-7a1c7102"
