[haiku]
name = "haiku"

[haiku.metadata]
torii_url = "https://api.cartridge.gg/x/dugdugdugdug/torii"
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia/"
relay_url = "/ip4/127.0.0.1/udp/9090/quic-v1"
database_url = "torii.db"
world_address = "0x340ea7578c677d1ef6e5ca96035a3e1058e244132e7b82e5867d4bcc91c9d37"
signer_address = "0x01BFC84464f990C09Cc0e5D64D18F54c3469fD5c467398BF31293051bAde1C39"
signer_private_key = "0x075362a844768f31c8058ce31aec3dd7751686440b4f220f410ae0c9bf042e60"

[haiku.context]
story = "In the heart of the ancient mountains lies a network of dark, treacherous mines. These mines, rich with precious minerals, are the workplace of funny, yet brave dwarfs. However, the mines are unstable and prone to sudden collapses, often trapping and killing the dwarfs in tragic, yet oddly humorous ways. The dwarfs, with their quirky personalities and relentless spirit, continue to dig deeper, driven by the promise of untold riches and the thrill of adventure. They swear and curse at the rocks, making spelling errors on their signs and maps. This perilous setting forms the backdrop for a tale of bravery, greed, and the dark humor of life underground."

[haiku.llm]
chat_completion_provider = "openai"
ai_model = "gpt-4o-mini"
ai_url = "https://api.openai.com/v1/chat/completions"
ai_token = ""

embedding_provider = "openai"
embedding_model = "text-embedding-3-small"
embedding_url = "https://api.openai.com/v1/embeddings"
embedding_token = ""

[haiku.db_config]
vector_size = "1536"
number_memory_to_retrieve = "5"

[[events]]
tag = "haiku-MineralFoundHaiku"

[events.prompt]
template = """
Minerals have been discovered! Make a story about leading upto the collapse of the mine.
Details:
- Seed: ${seed}
- Minerals: ${minerals}

If this discovery is reported by a dwarf, please ensure to verify the authenticity and check for any humorous spelling errors in their report.
"""

[events.db_keys]
storage_keys = []
retrieval_keys = []

[[events.keys_mapping]]
key = "id"
alias = ""
