kind = "DojoContract"
class_hash = "0x5f0722cb90e95de56bc3be45a976d3acc4906af98bdb94cc0058cc7ebb1a13"
original_class_hash = "0x5f0722cb90e95de56bc3be45a976d3acc4906af98bdb94cc0058cc7ebb1a13"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/dugdug-actions-3a561b6b.json"
reads = []
writes = []
init_calldata = []
tag = "dugdug-actions"
systems = [
    "spawn_miner",
    "buy_axe",
    "start_mining",
    "check_mining",
    "leave_mine",
    "create_mine",
]
manifest_name = "dugdug-actions-3a561b6b"
